ALTER TABLE Properties ALTER COLUMN PropertyID INT NOT NULL;
ALTER TABLE Properties ALTER COLUMN PropertyType VARCHAR(50) NOT NULL;
ALTER TABLE Properties ALTER COLUMN Location VARCHAR(100) NOT NULL;
ALTER TABLE Properties ALTER COLUMN Size_sqm FLOAT NOT NULL;
ALTER TABLE Properties ALTER COLUMN PriceUSD DECIMAL(12,2) NOT NULL;


ALTER TABLE Agents ALTER COLUMN AgentID INT NOT NULL;
ALTER TABLE Agents ALTER COLUMN FirstName VARCHAR(50) NOT NULL;
ALTER TABLE Agents ALTER COLUMN LastName VARCHAR(50) NOT NULL;
ALTER TABLE Agents ALTER COLUMN Phone VARCHAR(30) NULL; 
ALTER TABLE Agents ALTER COLUMN Email VARCHAR(100) NULL;


ALTER TABLE Clients ALTER COLUMN ClientID INT NOT NULL;
ALTER TABLE Clients ALTER COLUMN FirstName VARCHAR(50) NOT NULL;
ALTER TABLE Clients ALTER COLUMN LastName VARCHAR(50) NOT NULL;
ALTER TABLE Clients ALTER COLUMN Phone VARCHAR(30) NULL;
ALTER TABLE Clients ALTER COLUMN Email VARCHAR(100) NULL;

ALTER TABLE Visits ALTER COLUMN VisitID INT NOT NULL;
ALTER TABLE Visits ALTER COLUMN PropertyID INT NOT NULL;
ALTER TABLE Visits ALTER COLUMN ClientID INT NOT NULL;
ALTER TABLE Visits ALTER COLUMN AgentID INT NOT NULL;
ALTER TABLE Visits ALTER COLUMN VisitDate DATE NOT NULL;


ALTER TABLE Sales ALTER COLUMN SaleID INT NOT NULL;
ALTER TABLE Sales ALTER COLUMN PropertyID INT NOT NULL;
ALTER TABLE Sales ALTER COLUMN ClientID INT NOT NULL;
ALTER TABLE Sales ALTER COLUMN AgentID INT NOT NULL;
ALTER TABLE Sales ALTER COLUMN SaleDate DATE NOT NULL;
ALTER TABLE Sales ALTER COLUMN SalePrice DECIMAL(12,2) NOT NULL;

-- PK
ALTER TABLE 
Properties ADD CONSTRAINT PK_Properties PRIMARY KEY (PropertyID);

ALTER TABLE 
Agents ADD CONSTRAINT PK_Agents PRIMARY KEY (AgentID);

ALTER TABLE 
Clients ADD CONSTRAINT PK_Clients PRIMARY KEY (ClientID);

ALTER TABLE 
Sales ADD CONSTRAINT PK_Sales PRIMARY KEY (SaleID);

ALTER TABLE
Visits ADD CONSTRAINT PK_Visits PRIMARY KEY (VisitID);



--visits FK
ALTER TABLE 
Visits ADD CONSTRAINT FK_Visits_Properties 
   FOREIGN KEY (PropertyID) REFERENCES Properties(PropertyID);

ALTER TABLE 
Visits ADD CONSTRAINT FK_Visits_Clients 
   FOREIGN KEY (ClientID) REFERENCES Clients(ClientID);

ALTER TABLE 
Visits ADD CONSTRAINT FK_Visits_Agents 
   FOREIGN KEY (AgentID) REFERENCES Agents(AgentID);

--sales FK
ALTER TABLE 
Sales ADD CONSTRAINT FK_Sales_Properties 
   FOREIGN KEY (PropertyID) REFERENCES Properties(PropertyID);

ALTER TABLE 
Sales ADD CONSTRAINT FK_Sales_Clients 
   FOREIGN KEY (ClientID) REFERENCES Clients(ClientID);

ALTER TABLE 
Sales ADD CONSTRAINT FK_Sales_Agents 
   FOREIGN KEY (AgentID) REFERENCES Agents(AgentID);
